import { imageLazyLoader } from '$lib/Sprites/imageLazyLoader'

type TerrainData = SpriteObject & {
	connector: 0 | 1 | 2 | 3 | 4
	name: string
	description: string
	details:
		| 'dirty'
		| 'rough'
		| 'rugged'
		| 'clean'
		| 'pot-holes'
		| 'slippery'
		| 'sea'
		| 'impassable'
		| 'connector'
	ocean: boolean
	protection: number
	damage: number
	height: number
	drag: number
	modifiers: string[]
}

export const terrainData = [
	{
		url: 'game/play/terrain/plains.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Plains',
		description: 'Basic terrain',
		details: 'dirty',
		ocean: false,
		protection: 0.1,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/hills.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Hills',
		description: 'Gives ranged units an extended range',
		details: 'rough',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: ['CURMODS.Properties.Extra_Sight'],
	},
	{
		url: 'game/play/terrain/forest.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Forest',
		description: 'Gives defense boost',
		details: 'rough',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 5,
		drag: 2,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/mountain.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Mountain',
		description: 'Hard to traverse but gives strong defense',
		details: 'rugged',
		ocean: false,
		protection: 0.4,
		damage: 0,
		height: 50,
		drag: 2,
		modifiers: ['CURMODS.Properties.Extra_Sight'],
	},
	{
		url: 'game/play/terrain/road.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 1,
		name: 'Road',
		description: 'Easy to traverse but provides no defense',
		details: 'clean',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/canyon.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 1,
		name: 'Canyon',
		description: 'Dips down, but ranged units cannot target here',
		details: 'slippery',
		ocean: false,
		protection: 0.3,
		damage: 0,
		height: -10,
		drag: 1,
		modifiers: ['CURMODS.Properties.Trench'],
	},
	{
		url: 'game/play/terrain/wasteland.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Wasteland',
		description: 'Provides lots of defense, but costs health to rest on',
		details: 'dirty',
		ocean: false,
		protection: 0.5,
		damage: 10,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/volcano.png',
		frames: 1,
		xOffset: 0,
		yOffset: 34,
		connector: 0,
		name: 'Volcano',
		description: 'Impassable',
		details: 'impassable',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 100,
		drag: 100,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/enriched-ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Enriched Ore Deposit',
		description: 'Can be mined for money',
		details: 'pot-holes',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Ore Deposit',
		description: 'Can be mined for money',
		details: 'pot-holes',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/depleted-ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Depleted Ore Deposit',
		description: 'Can be mined for money',
		details: 'pot-holes',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/sea.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 3,
		name: 'Sea',
		description: 'Basic sea terrain',
		details: 'sea',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/reef.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Reef',
		description: 'Hard to traverse sea terrain',
		details: 'sea',
		ocean: true,
		protection: 0.1,
		damage: 0,
		height: 10,
		drag: 2,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/archipelago.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Archipelago',
		description: 'Rough sea terrain',
		details: 'sea',
		ocean: true,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/rock-formation.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Rock Formation',
		description: 'Rocky sea terrain',
		details: 'sea',
		ocean: true,
		protection: 0.7,
		damage: 20,
		height: 0,
		drag: 2,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/shore.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 3,
		name: 'Shore',
		description: 'An easy access to the sea',
		details: 'sea',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: ['CURMODS.Properties.Port'],
	},
	{
		url: 'game/play/terrain/bridge.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 4,
		name: 'Bridge',
		description: 'Connects two islands, but provides no defense',
		details: 'connector',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 10,
		drag: 1,
		modifiers: [],
	},
	{
		url: 'game/play/terrain/high-bridge.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 4,
		name: 'High Bridge',
		description: 'Connects two islands, and allows ships to pass, but provides no defense',
		details: 'connector',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 20,
		drag: 1,
		modifiers: [],
	},
] as TerrainData[]

export const terrainRenderer = imageLazyLoader('ground', terrainData)
