import { imageLazyLoader } from '$lib/Sprites/imageLazyLoader'

type TerrainData = {
	sprite: string
	spriteConnectorType: 0 | 1 | 2 | 3 | 4 | 5 | 8
	yOffset: number
	xOffset: number
	details:
		| 'dirty'
		| 'rough'
		| 'rugged'
		| 'clean'
		| 'pot-holes'
		| 'slippery'
		| 'sea'
		| 'impassable'
		| 'connector'
	name: string
	description: string
	ocean: boolean
	protection: number
	damage: number
	height: number
	drag: number
	modifiers: string[]
}

const localData = [
	{
		sprite: 'game/play/terrain/plains/0.png',
		spriteConnectorType: 2,
		xOffset: 0,
		yOffset: 0,
		details: 'dirty',
		name: 'Plains',
		description: 'Basic terrain',
		ocean: false,
		protection: 0.1,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/hill/0.png',
		spriteConnectorType: 2,
		xOffset: 0,
		yOffset: 0,
		details: 'rough',
		name: 'Hill',
		description: 'Gives ranged units an extended range',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: ['CURMODS.Properties.Extra_Sight'],
	},
	{
		sprite: 'game/play/terrain/forest/0.png',
		spriteConnectorType: 2,
		xOffset: 0,
		yOffset: 0,
		details: 'rough',
		name: 'Forest',
		description: 'Gives defense boost',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 5,
		drag: 2,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/mountain/0.png',
		spriteConnectorType: 2,
		xOffset: 0,
		yOffset: 0,
		details: 'rugged',
		name: 'Mountain',
		description: 'Hard to traverse but gives strong defense',
		ocean: false,
		protection: 0.4,
		damage: 0,
		height: 50,
		drag: 2,
		modifiers: ['CURMODS.Properties.Extra_Sight'],
	},
	{
		sprite: 'game/play/terrain/road/0.png',
		spriteConnectorType: 1,
		xOffset: 0,
		yOffset: 0,
		details: 'clean',
		name: 'Road',
		description: 'Easy to traverse but provides no defense',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/canyon/0.png',
		spriteConnectorType: 1,
		xOffset: 0,
		yOffset: 0,
		details: 'slippery',
		name: 'Canyon',
		description: 'Dips down, but ranged units cannot target here',
		ocean: false,
		protection: 0.3,
		damage: 0,
		height: -10,
		drag: 1,
		modifiers: ['CURMODS.Properties.Trench'],
	},
	{
		sprite: 'game/play/terrain/wasteland/0.png',
		spriteConnectorType: 0,
		xOffset: 0,
		yOffset: 0,
		details: 'dirty',
		name: 'Wasteland',
		description: 'Provides lots of defense, but costs health to rest on',
		ocean: false,
		protection: 0.5,
		damage: 10,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/volcano/0.png',
		spriteConnectorType: 4,
		xOffset: 0,
		yOffset: 34,
		details: 'impassable',
		name: 'Volcano',
		description: 'Impassable',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 100,
		drag: 100,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/enriched-ore-deposit/0.png',
		spriteConnectorType: 0,
		xOffset: 0,
		yOffset: 0,
		details: 'pot-holes',
		name: 'Enriched Ore Deposit',
		description: 'Can be mined for money',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/ore-deposit/0.png',
		spriteConnectorType: 0,
		xOffset: 0,
		yOffset: 0,
		details: 'pot-holes',
		name: 'Ore Deposit',
		description: 'Can be mined for money',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/depleted-ore-deposit/0.png',
		spriteConnectorType: 0,
		xOffset: 0,
		yOffset: 0,
		details: 'pot-holes',
		name: 'Depleted Ore Deposit',
		description: 'Can be mined for money',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/sea/0.png',
		spriteConnectorType: 3,
		xOffset: 0,
		yOffset: 0,
		details: 'sea',
		name: 'Sea',
		description: 'Basic sea terrain',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/reef/0.png',
		spriteConnectorType: 5,
		xOffset: 0,
		yOffset: 0,
		details: 'sea',
		name: 'Reef',
		description: 'Hard to traverse sea terrain',
		ocean: true,
		protection: 0.1,
		damage: 0,
		height: 10,
		drag: 2,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/archipelago/0.png',
		spriteConnectorType: 5,
		xOffset: 0,
		yOffset: 0,
		details: 'sea',
		name: 'Archipelago',
		description: 'Rough sea terrain',
		ocean: true,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/rock-formation/0.png',
		spriteConnectorType: 5,
		xOffset: 0,
		yOffset: 0,
		details: 'sea',
		name: 'Rock Formation',
		description: 'Rocky sea terrain',
		ocean: true,
		protection: 0.7,
		damage: 20,
		height: 0,
		drag: 2,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/shore/0.png',
		spriteConnectorType: 3,
		xOffset: 0,
		yOffset: 0,
		details: 'sea',
		name: 'Shore',
		description: 'An easy access to the sea',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: ['CURMODS.Properties.Port'],
	},
	{
		sprite: 'game/play/terrain/bridge/0.png',
		spriteConnectorType: 8,
		xOffset: 0,
		yOffset: 0,
		details: 'connector',
		name: 'Bridge',
		description: 'Connects two islands, but provides no defense',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 10,
		drag: 1,
		modifiers: [],
	},
	{
		sprite: 'game/play/terrain/high-bridge/0.png',
		spriteConnectorType: 8,
		xOffset: 0,
		yOffset: 0,
		details: 'connector',
		name: 'High Bridge',
		description: 'Connects two islands, and allows ships to pass, but provides no defense',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 20,
		drag: 1,
		modifiers: [],
	},
] as TerrainData[]

export const terrainData = imageLazyLoader('ground', localData)
