import { imageLazyLoader } from '$lib/Sprites/imageLazyLoader'
import type { modifierData } from './modifier'

type TerrainData = ObjectAssetMeta & {
	connector: 0 | 1 | 2 | 3 | 4 | 5
	// Sprite column to show in the map-editor palette. Autotiled terrains (border
	// connector) render their state-0 frame as open water, so Shore would look
	// identical to Sea in the palette. Point it at a coastline frame instead.
	editorState?: number
	name: string
	description: string
	details: 'clean' | 'dirty' | 'rough' | 'slippery' | 'rugged' | 'impassable'
	ocean: boolean
	protection: number
	damage: number
	height: number
	drag: number
	modifiers: (keyof typeof modifierData)[]
}

export const terrainData: TerrainData[] = [
	{
		url: '/game/play/terrain/plains.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Plains',
		description: 'Basic terrain',
		details: 'dirty',
		ocean: false,
		protection: 0.1,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/hills.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Hills',
		description: 'Gives ranged units an extended range',
		details: 'rough',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: ['Extra_Sight'],
	},
	{
		url: '/game/play/terrain/forest.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Forest',
		description: 'Gives a defense boost and hides units inside it from distant enemies in fog',
		details: 'rough',
		ocean: false,
		protection: 0.2,
		damage: 0,
		height: 5,
		drag: 2,
		modifiers: ['Conceals'],
	},
	{
		url: '/game/play/terrain/mountain.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 2,
		name: 'Mountain',
		description: 'Hard to traverse but gives strong defense',
		details: 'rugged',
		ocean: false,
		protection: 0.4,
		damage: 0,
		height: 50,
		drag: 2,
		modifiers: ['Extra_Sight'],
	},
	{
		url: '/game/play/terrain/road.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 1,
		name: 'Road',
		description: 'Easy to traverse but provides no defense',
		details: 'clean',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/canyon.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 1,
		name: 'Canyon',
		description: 'Dips down, but ranged units cannot target here',
		details: 'slippery',
		ocean: false,
		protection: 0.5,
		damage: 0,
		height: -10,
		drag: 1,
		modifiers: ['Trench'],
	},
	{
		url: '/game/play/terrain/wasteland.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Wasteland',
		description: 'Provides lots of defense, but costs health to rest on',
		details: 'dirty',
		ocean: false,
		protection: 0.5,
		damage: 10,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/volcano.png',
		frames: 1,
		xOffset: 0,
		yOffset: 34,
		connector: 0,
		name: 'Volcano',
		description: 'Impassable',
		details: 'impassable',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 100,
		drag: 100,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/enriched-ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Enriched Ore Deposit',
		description: 'Can be mined for money',
		details: 'clean',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Ore Deposit',
		description: 'Can be mined for money',
		details: 'rough',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/depleted-ore-deposit.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Depleted Ore Deposit',
		description: 'Mined out, no funds left',
		details: 'rugged',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/sea.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 3,
		name: 'Sea',
		description: 'Basic sea terrain',
		details: 'clean',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/reef.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Reef',
		description: 'Hard to traverse sea terrain',
		details: 'dirty',
		ocean: true,
		protection: 0.1,
		damage: 0,
		height: 10,
		drag: 2,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/archipelago.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Archipelago',
		description: 'Rough sea terrain',
		details: 'rough',
		ocean: true,
		protection: 0.2,
		damage: 0,
		height: 20,
		drag: 2,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/rock-formation.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Rock Formation',
		description: 'Rocky sea terrain',
		details: 'rugged',
		ocean: true,
		protection: 0.7,
		damage: 20,
		height: 0,
		drag: 2,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/shore.png',
		frames: 3,
		xOffset: 0,
		yOffset: 0,
		connector: 3,
		editorState: 11,
		name: 'Shore',
		description: 'An easy access to the sea',
		details: 'rough',
		ocean: true,
		protection: 0,
		damage: 0,
		height: 0,
		drag: 1,
		modifiers: ['Port', 'Amphibious', 'Shallow'],
	},
	{
		url: '/game/play/terrain/bridge.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 4,
		name: 'Bridge',
		description: 'Connects two islands, but provides no defense',
		details: 'clean',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 10,
		drag: 1,
		modifiers: [],
	},
	{
		url: '/game/play/terrain/high-bridge.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 4,
		name: 'High Bridge',
		description: 'Connects two islands, and allows ships to pass, but provides no defense',
		details: 'clean',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 20,
		drag: 1,
		modifiers: ['Amphibious'],
	},
	{
		url: '/game/play/terrain/rampart.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		connector: 0,
		name: 'Rampart',
		description: 'A solid wall. Impassable, and indirect fire cannot reach past it.',
		details: 'impassable',
		ocean: false,
		protection: 0,
		damage: 0,
		height: 30,
		drag: 1,
		modifiers: ['Bulwark'],
	},
	// Left behind when a Scorcher burns Forest away (see modifiers/burn.ts). Charred
	// stumps and ash — visually the forest that was, not a toxic wasteland. The
	// canopy that concealed and sheltered units is gone, so it grants almost no cover
	// and no concealment, but it isn't poisoned ground, so it costs no health to hold.
	// APPEND-ONLY: terrain is stored by index in saved maps, so this must stay last.
	{
		url: '/game/play/terrain/scorched.png',
		frames: 1,
		xOffset: 0,
		yOffset: 0,
		// connector 5 (type-border): the burn scar autotiles against other Charred
		// Forest tiles using the Sea's border-plus-inner-corner scheme (matched on
		// terrain type instead of the ocean flag), so concave junctions between arms of
		// a scar fill cleanly instead of leaving jagged notches. 20-frame sheet: 16
		// border-base states + 4 inner-corner overlays (see spriteConnector / paint).
		connector: 5,
		name: 'Charred Forest',
		description:
			'Burnt-out woodland — charred stumps and ash. Almost no cover, and no concealment.',
		details: 'rough',
		ocean: false,
		protection: 0.1,
		damage: 0,
		height: 1,
		drag: 2,
		modifiers: [],
	},
]

export const terrainRenderer = imageLazyLoader('ground', terrainData)
