import { imageLazyLoader } from '$lib/Sprites/imageLazyLoader'
import type { modifierData } from './modifier'

type UnitData = ObjectAssetMeta & {
	name: string
	description: string
	type: 'ground' | 'air' | 'sea'
	weaponType: 'light' | 'medium' | 'heavy'
	armorType: 'light' | 'medium' | 'heavy'
	movementType:
		| 'none'
		| 'foot'
		| 'wheel'
		| 'tank'
		| 'low air'
		| 'high air'
		| 'boat'
		| 'warship'
		| 'submarine'
	power: number
	health: number
	movement: number
	sight: number
	cost: number
	range: [number, number]
	actable: boolean
	modifiers: (keyof typeof modifierData)[]
}

const COMMON_RANGE: [number, number] = [1, 1]

export const unitData: UnitData[] = [
	{
		url: '/game/play/unit/idle/strike-commando.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Strike Commando',
		description: 'Basic land unit',
		type: 'ground',
		weaponType: 'light',
		armorType: 'light',
		movementType: 'foot',
		power: 20,
		health: 40,
		movement: 3,
		sight: 2,
		cost: 75,
		range: COMMON_RANGE,
		actable: true,
		modifiers: [
			'Start_Turn.Capture',
			'Move.Tracking',
			'Self_Action.Transport',
			'Self_Action.Repairable',
		],
	},
	{
		url: '/game/play/unit/idle/heavy-commando.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Heavy Commando',
		description: 'Basic land unit',
		type: 'ground',
		weaponType: 'heavy',
		armorType: 'light',
		movementType: 'foot',
		power: 35,
		health: 40,
		movement: 3,
		sight: 2,
		cost: 100,
		range: COMMON_RANGE,
		actable: true,
		modifiers: [
			'Start_Turn.Capture',
			'Move.Tracking',
			'Self_Action.Transport',
			'Self_Action.Repairable',
		],
	},
	{
		url: '/game/play/unit/idle/flak-tank.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Flak Tank',
		description: 'Very effective against air units',
		type: 'ground',
		weaponType: 'light',
		armorType: 'medium',
		movementType: 'tank',
		power: 17,
		health: 70,
		movement: 6,
		sight: 3,
		cost: 240,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Can_Attack.Air_Raid', 'Damage.Flak', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/scorpion-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Scorpion Tank',
		description: 'Basic tank unit',
		type: 'ground',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'tank',
		power: 35,
		health: 70,
		movement: 6,
		sight: 3,
		cost: 270,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Damage.Fast_Attack', 'Self_Action.Repairable', 'Can_Attack.Bombard'],
	},
	{
		url: '/game/play/unit/idle/lance-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Lance Tank',
		description: 'Can hit space directly behind enemy',
		type: 'ground',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'tank',
		power: 35,
		health: 70,
		movement: 6,
		sight: 3,
		cost: 270,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Attack.Lance', 'Self_Action.Repairable', 'Can_Attack.Bombard'],
	},
	{
		url: '/game/play/unit/idle/spider-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Spider Tank',
		description: 'Can climb mountains',
		type: 'ground',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'foot',
		power: 40,
		health: 40,
		movement: 4,
		sight: 3,
		cost: 250,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Attack.Stun', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/stealth-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Stealth Tank',
		description: 'Can hide itself',
		type: 'ground',
		weaponType: 'light',
		armorType: 'medium',
		movementType: 'tank',
		power: 30,
		health: 40,
		movement: 5,
		sight: 3,
		cost: 340,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['End_Turn.Cloak', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/annihilator-tank.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Annihilator Tank',
		description: 'Massive tank',
		type: 'ground',
		weaponType: 'heavy',
		armorType: 'heavy',
		movementType: 'tank',
		power: 70,
		health: 140,
		movement: 4,
		sight: 3,
		cost: 525,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Damage.Slow_Attack', 'Self_Action.Repairable', 'Can_Attack.Bombard'],
	},
	{
		url: '/game/play/unit/idle/mortar-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Mortar Truck',
		description: 'Heavy distanced attack but with short range',
		type: 'ground',
		weaponType: 'medium',
		armorType: 'light',
		movementType: 'wheel',
		power: 48,
		health: 50,
		movement: 5,
		sight: 3,
		cost: 285,
		range: [2, 3],
		actable: true,
		modifiers: ['Can_Attack.Counter_Range', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/rocket-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Rocket Truck',
		description: 'Weaker distanced attack but with long range',
		type: 'ground',
		weaponType: 'heavy',
		armorType: 'light',
		movementType: 'wheel',
		power: 40,
		health: 40,
		movement: 6,
		sight: 4,
		cost: 470,
		range: [3, 5],
		actable: true,
		modifiers: ['Can_Attack.Counter_Range', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/jammer-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Jammer Truck',
		description: 'Stops air units from entering jammed area and uncloaks hidden units',
		type: 'ground',
		weaponType: 'light',
		armorType: 'light',
		movementType: 'wheel',
		power: 0,
		health: 50,
		movement: 5,
		sight: 2,
		cost: 300,
		range: [2, 3], // enemies attacked will be partially disabled
		actable: true,
		modifiers: ['Move.Radar', 'Idle.Jamming', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/warmachine.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Warmachine',
		description: 'Creates other units',
		type: 'ground',
		weaponType: 'heavy',
		armorType: 'medium',
		movementType: 'tank',
		power: 60,
		health: 75,
		movement: 3,
		sight: 3,
		cost: 525,
		range: [2, 3],
		actable: true,
		modifiers: [
			'Self_Action.Miner',
			'Self_Action.Builder',
			'Self_Action.Repairable',
			'Death.Insta_Lose',
		],
	},
	{
		url: '/game/play/unit/idle/intrepid.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Intrepid',
		description: 'Can capture sea buildings',
		type: 'sea',
		weaponType: 'light',
		armorType: 'light',
		movementType: 'boat',
		power: 15,
		health: 50,
		movement: 6,
		sight: 5,
		cost: 200,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Start_Turn.Capture', 'Move.Tracking', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/corvette.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Corvette',
		description: 'Basic sea unit',
		type: 'sea',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'warship',
		power: 45,
		health: 90,
		movement: 5,
		sight: 4,
		cost: 500,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Can_Attack.Ground_Assult', 'Damage.Fast_Attack'],
	},
	{
		url: '/game/play/unit/idle/hunter-support.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Hunter Support',
		description: 'Can attack air units',
		type: 'sea',
		weaponType: 'light',
		armorType: 'medium',
		movementType: 'boat',
		power: 17,
		health: 90,
		movement: 5,
		sight: 4,
		cost: 450,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Can_Attack.Air_Raid', 'Damage.Flak', 'Move.Tracking', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/u-boat.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'U-Boat',
		description: 'Can hide underwater',
		type: 'sea',
		weaponType: 'heavy',
		armorType: 'light',
		movementType: 'submarine',
		power: 35,
		health: 25,
		movement: 4,
		sight: 4,
		cost: 475,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['End_Turn.Cloak', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/raptor-fighter.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Raptor Fighter',
		description: 'Basic air unit',
		type: 'air',
		weaponType: 'light',
		armorType: 'light',
		movementType: 'high air',
		power: 25,
		health: 50,
		movement: 8,
		sight: 5,
		cost: 235,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Can_Attack.Air_Raid', 'Self_Action.Irreparable'],
	},
	{
		url: '/game/play/unit/idle/condor-bomber.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Condor Bomber',
		description: 'Drops bombs of massive damage',
		type: 'air',
		weaponType: 'heavy',
		armorType: 'medium',
		movementType: 'high air',
		power: 70,
		health: 40,
		movement: 4,
		sight: 3,
		cost: 600,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Self_Action.Repairable', 'Can_Attack.Bombard'],
	},
	{
		url: '/game/play/unit/idle/vulture-drone.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Vulture Drone',
		description: 'Can move again if attack kills',
		type: 'air',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'low air',
		power: 30,
		health: 55,
		movement: 5,
		sight: 5,
		cost: 550,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['End_Turn.Vulture', 'Self_Action.Repairable', 'Can_Attack.Bombard'],
	},
	{
		url: '/game/play/unit/idle/turret.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Turret',
		description: 'Basic turret unit',
		type: 'ground',
		weaponType: 'medium',
		armorType: 'medium',
		movementType: 'none',
		power: 40,
		health: 100,
		movement: 0,
		sight: 5,
		cost: 0,
		range: [2, 5],
		actable: true,
		modifiers: ['Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/blockade.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Blockade',
		description: 'Cannot move or attack, but enemies cannot cross',
		type: 'ground',
		weaponType: 'light',
		armorType: 'medium',
		movementType: 'none',
		power: 0,
		health: 70,
		movement: 0,
		sight: 0,
		cost: 0,
		range: [0, 0],
		actable: false,
		modifiers: ['Self_Action.Irreparable'],
	},
	{
		url: '/game/play/unit/idle/battle-cruiser.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Battle Cruiser',
		description: 'Can attack from the farthest distance in the game',
		type: 'sea',
		weaponType: 'heavy',
		armorType: 'heavy',
		movementType: 'warship',
		power: 55,
		health: 140,
		movement: 4,
		sight: 6,
		cost: 800,
		range: [2, 6],
		actable: true,
		modifiers: ['Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/leviathan.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Leviathan',
		description: 'Can ship across water',
		type: 'sea',
		weaponType: 'heavy',
		armorType: 'medium',
		movementType: 'submarine',
		power: 0,
		health: 60,
		movement: 4,
		sight: 2,
		cost: 0,
		range: COMMON_RANGE,
		actable: true,
		modifiers: ['Self_Action.Land', 'Self_Action.Repairable'],
	},
	{
		url: '/game/play/unit/idle/transporter.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Transporter',
		description: 'Can transport a non-air unit through the air',
		type: 'air',
		weaponType: 'light',
		armorType: 'light',
		movementType: 'low air',
		power: 0,
		health: 50,
		movement: 6,
		sight: 3,
		cost: 0,
		range: [0, 0],
		actable: true,
		modifiers: ['Self_Action.Land', 'Self_Action.Repairable'],
	},
]

export const unitRenderer = imageLazyLoader('units', unitData, 4)
