import { imageLazyLoader } from '$lib/Sprites/imageLazyLoader'

type UnitData = SpriteObject & {
	name: string
	description: string
	type: number
	maxHealth: number
	armor: number
	power: number
	weaponType: number
	movement: number
	movementType: number
	range: [number, number]
	sight: number
	cost: number
	actable: boolean
	modifiers: string[]
	attackSFX: string | null
	moveSFX: string | null
}

const COMMON_RANGE = [1, 1]

export const unitData = [
	{
		url: '/game/play/units/idle/strike-commando.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Strike Commando',
		description: 'Basic land unit',
		type: 0,
		maxHealth: 40,
		armor: 0,
		power: 20,
		weaponType: 0,
		movement: 3,
		movementType: 0,
		range: COMMON_RANGE,
		sight: 2,
		cost: 75,
		actable: true,
		modifiers: [
			'CURMODS.Start_Turn.Capture',
			'CURMODS.Move.Tracking',
			'CURMODS.Self_Action.Transport',
			'CURMODS.Self_Action.Repairable',
		],
		attackSFX: `SFXs.Retrieve('light gun')`,
		moveSFX: `SFXs.Retrieve('footstep')`,
	},
	{
		url: '/game/play/units/idle/heavy-commando.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Heavy Commando',
		description: 'Basic land unit',
		type: 0,
		maxHealth: 40,
		armor: 0,
		power: 35,
		weaponType: 2,
		movement: 3,
		movementType: 0,
		range: COMMON_RANGE,
		sight: 2,
		cost: 100,
		actable: true,
		modifiers: [
			'CURMODS.Start_Turn.Capture',
			'CURMODS.Move.Tracking',
			'CURMODS.Self_Action.Transport',
			'CURMODS.Self_Action.Repairable',
		],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('footstep')`,
	},
	{
		url: '/game/play/units/idle/flak-tank.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Flak Tank',
		description: 'Very effective against air units',
		type: 0,
		maxHealth: 70,
		armor: 1,
		power: 17,
		weaponType: 0,
		movement: 6,
		movementType: 2,
		range: COMMON_RANGE,
		sight: 3,
		cost: 240,
		actable: true,
		modifiers: [
			'CURMODS.Can_Attack.Air_Raid',
			'CURMODS.Damage.Flak',
			'CURMODS.Self_Action.Repairable',
		],
		attackSFX: `SFXs.Retrieve('machine gun')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/scorpion-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Scorpion Tank',
		description: 'Basic tank unit',
		type: 0,
		maxHealth: 70,
		armor: 1,
		power: 35,
		weaponType: 1,
		movement: 6,
		movementType: 2,
		range: COMMON_RANGE,
		sight: 3,
		cost: 270,
		actable: true,
		modifiers: [
			'CURMODS.Damage.Fast_Attack',
			'CURMODS.Self_Action.Repairable',
			'CURMODS.Can_Attack.Bombard',
		],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/lance-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Lance Tank',
		description: 'Can hit space directly behind enemy',
		type: 0,
		maxHealth: 70,
		armor: 1,
		power: 35,
		weaponType: 1,
		movement: 6,
		movementType: 2,
		range: COMMON_RANGE,
		sight: 3,
		cost: 270,
		actable: true,
		modifiers: [
			'CURMODS.Attack.Lance',
			'CURMODS.Self_Action.Repairable',
			'CURMODS.Can_Attack.Bombard',
		],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/spider-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Spider Tank',
		description: 'Can climb mountains',
		type: 0,
		maxHealth: 40,
		armor: 1,
		power: 40,
		weaponType: 1,
		movement: 4,
		movementType: 0,
		range: COMMON_RANGE,
		sight: 3,
		cost: 250,
		actable: true,
		modifiers: ['CURMODS.Attack.Stun', 'CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('light gun')`,
		moveSFX: `SFXs.Retrieve('footstep')`,
	},
	{
		url: '/game/play/units/idle/stealth-tank.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Stealth Tank',
		description: 'Can hide itself',
		type: 0,
		maxHealth: 40,
		armor: 1,
		power: 30,
		weaponType: 0,
		movement: 5,
		movementType: 2,
		range: COMMON_RANGE,
		sight: 3,
		cost: 340,
		actable: true,
		modifiers: ['CURMODS.End_Turn.Cloak', 'CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('distance gun')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/annihilator-tank.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Annihilator Tank',
		description: 'Massive tank',
		type: 0,
		maxHealth: 140,
		armor: 2,
		power: 70,
		weaponType: 2,
		movement: 4,
		movementType: 2,
		range: COMMON_RANGE,
		sight: 3,
		cost: 525,
		actable: true,
		modifiers: [
			'CURMODS.Damage.Slow_Attack',
			'CURMODS.Self_Action.Repairable',
			'CURMODS.Can_Attack.Bombard',
		],
		attackSFX: `SFXs.Retrieve('explosion')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/mortar-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Mortar Truck',
		description: 'Heavy distanced attack but with short range',
		type: 0,
		maxHealth: 50,
		armor: 0,
		power: 48,
		weaponType: 1,
		movement: 5,
		movementType: 1,
		range: [2, 3],
		sight: 3,
		cost: 285,
		actable: true,
		modifiers: ['CURMODS.Can_Attack.Counter_Range', 'CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/rocket-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Rocket Truck',
		description: 'Weaker distanced attack but with long range',
		type: 0,
		maxHealth: 40,
		armor: 0,
		power: 40,
		weaponType: 2,
		movement: 6,
		movementType: 1,
		range: [3, 5],
		sight: 4,
		cost: 470,
		actable: true,
		modifiers: ['CURMODS.Can_Attack.Counter_Range', 'CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('explosion')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/jammer-truck.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Jammer Truck',
		description: 'Stops air units from entering jammed area and uncloaks hidden units',
		type: 0,
		maxHealth: 50,
		armor: 0,
		power: 0,
		weaponType: -1,
		movement: 5,
		movementType: 1,
		range: [], // enemies attacked will be partially disabled
		sight: 2,
		cost: 300,
		actable: true,
		modifiers: ['CURMODS.Move.Radar', 'CURMODS.Idle.Jamming', 'CURMODS.Self_Action.Repairable'],
		attackSFX: null,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/warmachine.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Warmachine',
		description: 'Creates other units',
		type: 0,
		maxHealth: 75,
		armor: 1,
		power: 60,
		weaponType: 2,
		movement: 3,
		movementType: 2,
		range: [2, 3],
		sight: 3,
		cost: 525,
		Cash: 2000,
		actable: true,
		modifiers: [
			'CURMODS.Self_Action.Miner',
			'CURMODS.Self_Action.Builder',
			'CURMODS.Self_Action.Repairable',
			'CURMODS.Death.Insta_Lose',
		],
		attackSFX: `SFXs.Retrieve('explosion')`,
		moveSFX: `SFXs.Retrieve('car engine')`,
	},
	{
		url: '/game/play/units/idle/intrepid.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Intrepid',
		description: 'Can capture sea buildings',
		type: 2,
		maxHealth: 50,
		armor: 0,
		power: 15,
		weaponType: 0,
		movement: 6,
		movementType: 6,
		rlow: false,
		sange: COMMON_RANGE,
		cost: 200,
		actable: true,
		modifiers: [
			'CURMODS.Start_Turn.Capture',
			'CURMODS.Move.Tracking',
			'CURMODS.Self_Action.Repairable',
		],
		attackSFX: `SFXs.Retrieve('machine gun')`,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/corvette.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Corvette',
		description: 'Basic sea unit',
		type: 2,
		maxHealth: 90,
		armor: 1,
		power: 45,
		weaponType: 1,
		movement: 5,
		movementType: 8,
		range: COMMON_RANGE,
		sight: 4,
		cost: 500,
		actable: true,
		modifiers: ['CURMODS.Can_Attack.Ground_Assult', 'CURMODS.Damage.Fast_Attack'],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/hunter-support.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Hunter Support',
		description: 'Can attack air units',
		type: 2,
		maxHealth: 90,
		armor: 1,
		power: 17,
		weaponType: 0,
		movement: 5,
		movementType: 6,
		range: COMMON_RANGE,
		sight: 4,
		cost: 450,
		actable: true,
		modifiers: [
			'CURMODS.Can_Attack.Air_Raid',
			'CURMODS.Damage.Flak',
			'CURMODS.Move.Tracking',
			'CURMODS.Self_Action.Repairable',
		],
		attackSFX: `SFXs.Retrieve('machine gun')`,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/u-boat.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'U-Boat',
		description: 'Can hide underwater',
		type: 2,
		maxHealth: 25,
		armor: 0,
		power: 35,
		weaponType: 2,
		movement: 4,
		movementType: 7,
		range: COMMON_RANGE,
		sight: 4,
		cost: 475,
		actable: true,
		modifiers: ['CURMODS.End_Turn.Cloak', 'CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/raptor-fighter.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Raptor Fighter',
		description: 'Basic air unit',
		type: 1,
		maxHealth: 50,
		armor: 0,
		power: 25,
		weaponType: 0,
		movement: 8,
		movementType: 4,
		range: COMMON_RANGE,
		sight: 5,
		cost: 235,
		actable: true,
		modifiers: ['CURMODS.Can_Attack.Air_Raid', 'CURMODS.Self_Action.Irreparable'],
		attackSFX: `SFXs.Retrieve('machine gun')`,
		moveSFX: `SFXs.Retrieve('jet')`,
	},
	{
		url: '/game/play/units/idle/condor-bomber.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Condor Bomber',
		description: 'Drops bombs of massive damage',
		type: 1,
		maxHealth: 40,
		armor: 1,
		power: 70,
		weaponType: 2,
		movement: 4,
		movementType: 4,
		range: COMMON_RANGE,
		sight: 3,
		cost: 600,
		actable: true,
		modifiers: ['CURMODS.Self_Action.Repairable', 'CURMODS.Can_Attack.Bombard'],
		attackSFX: `SFXs.Retrieve('explosion')`,
		moveSFX: `SFXs.Retrieve('air')`,
	},
	{
		url: '/game/play/units/idle/vulture-drone.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Vulture Drone',
		description: 'Can move again if attack kills',
		type: 1,
		maxHealth: 55,
		armor: 1,
		power: 30,
		weaponType: 1,
		movement: 5,
		movementType: 3,
		range: COMMON_RANGE,
		sight: 5,
		cost: 550,
		actable: true,
		modifiers: [
			'CURMODS.End_Turn.Vulture',
			'CURMODS.Self_Action.Repairable',
			'CURMODS.Can_Attack.Bombard',
		],
		attackSFX: `SFXs.Retrieve('distance gun')`,
		moveSFX: `SFXs.Retrieve('jet')`,
	},
	{
		url: '/game/play/units/idle/turret.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Turret',
		description: 'Basic turret unit',
		type: 0,
		maxHealth: 100,
		armor: 1,
		power: 40,
		weaponType: 1,
		movement: 0,
		movementType: 9,
		range: [2, 5],
		sight: 5,
		cost: 0,
		actable: true,
		modifiers: ['CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('distance gun')`,
		moveSFX: `SFXs.Retrieve('quite')`,
	},
	{
		url: '/game/play/units/idle/blockade.png',
		frames: 4,
		yOffset: 0,
		xOffset: 0,
		name: 'Blockade',
		description: 'Cannot move or attack, but enemies cannot cross',
		type: 0,
		maxHealth: 70,
		armor: 1,
		power: 0,
		weaponType: 0,
		movement: 0,
		movementType: 9,
		range: [0, 0],
		sight: 0,
		cost: 0,
		actable: false,
		modifiers: ['CURMODS.Self_Action.Irreparable'],
		attackSFX: null,
		moveSFX: `SFXs.Retrieve('quite')`,
	},
	{
		url: '/game/play/units/idle/battle-cruiser.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Battle Cruiser',
		description: 'Can attack from the farthest distance in the game',
		type: 2,
		maxHealth: 140,
		armor: 2,
		power: 55,
		weaponType: 2,
		movement: 4,
		movementType: 8,
		range: [2, 6],
		sight: 6,
		cost: 800,
		actable: true,
		modifiers: ['CURMODS.Self_Action.Repairable'],
		attackSFX: `SFXs.Retrieve('big gun')`,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/leviathan.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Leviathan',
		description: 'Can ship across water',
		type: 2,
		maxHealth: 60,
		armor: 1,
		power: 0,
		weaponType: 2,
		movement: 4,
		movementType: 7,
		range: COMMON_RANGE,
		sight: 2,
		cost: 0,
		actable: true,
		modifiers: ['CURMODS.Self_Action.Land', 'CURMODS.Self_Action.Repairable'],
		attackSFX: null,
		moveSFX: `SFXs.Retrieve('boat')`,
	},
	{
		url: '/game/play/units/idle/transporter.png',
		frames: 4,
		yOffset: 60,
		xOffset: 0,
		name: 'Transporter',
		description: 'Can transport a non-air unit through the air',
		type: 1,
		maxHealth: 50,
		armor: 0,
		power: 0,
		weaponType: 0,
		movement: 6,
		movementType: 3,
		range: [0, 0],
		sight: 3,
		cost: 0,
		actable: true,
		modifiers: ['CURMODS.Self_Action.Land', 'CURMODS.Self_Action.Repairable'],
		attackSFX: null,
		moveSFX: `SFXs.Retrieve('air')`,
	},
] as UnitData[]

export const unitRenderer = imageLazyLoader('units', unitData, 4)
