import { browser } from '$app/environment'
import { generateSigningKey, type PublicKeyJwk } from '$lib/Security/frameSigning'

/**
 * The browser's signing key for one match (see `frameSigning.ts`).
 *
 * Generated once per room and kept in IndexedDB, which can hold a CryptoKey
 * whose private half is not extractable: a reload finds the same key, so the
 * seat's registered public key stays valid and nothing is re-registered. A
 * browser with no usable IndexedDB gets a key for the life of the tab and
 * registers it again after a reload, which costs one write.
 */
export type MatchKey = {
	privateKey: CryptoKey
	publicJwk: PublicKeyJwk
	/** Freshly generated by this call, so the seat does not know it yet. */
	created: boolean
}

const DB_NAME = 'thunderlite-match-keys'
const STORE = 'keys'

const openDb = (): Promise<IDBDatabase | null> =>
	new Promise((resolve) => {
		if (!browser || typeof indexedDB === 'undefined') return resolve(null)
		try {
			const request = indexedDB.open(DB_NAME, 1)
			request.onupgradeneeded = () => request.result.createObjectStore(STORE)
			request.onsuccess = () => resolve(request.result)
			request.onerror = () => resolve(null)
			request.onblocked = () => resolve(null)
		} catch {
			resolve(null)
		}
	})

const idb = <T>(
	db: IDBDatabase,
	mode: IDBTransactionMode,
	run: (store: IDBObjectStore) => IDBRequest<T>
) =>
	new Promise<T | null>((resolve) => {
		try {
			const tx = db.transaction(STORE, mode)
			const request = run(tx.objectStore(STORE))
			request.onsuccess = () => resolve(request.result)
			request.onerror = () => resolve(null)
		} catch {
			resolve(null)
		}
	})

type Stored = { privateKey: CryptoKey; publicJwk: PublicKeyJwk }

export const loadOrCreateMatchKey = async (session: string): Promise<MatchKey> => {
	const db = await openDb()
	if (db) {
		const stored = await idb<Stored | undefined>(db, 'readonly', (s) => s.get(session))
		if (stored?.privateKey && stored.publicJwk) {
			return { privateKey: stored.privateKey, publicJwk: stored.publicJwk, created: false }
		}
	}
	const fresh = await generateSigningKey()
	const record: Stored = { privateKey: fresh.privateKey, publicJwk: fresh.publicJwk }
	if (db) await idb(db, 'readwrite', (s) => s.put(record, session))
	return { ...record, created: true }
}
