name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          PUBLIC_URL: ${{ env.PUBLIC_URL }}
          PUBLIC_GAME_NAME: ${{ env.PUBLIC_GAME_NAME }}
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
